### ISSUE TITLE
Notifications Components :: NotificationsWidget

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/admin-ui-components#13]
## NotificationsWidget

<img width="470" alt="Screen Shot 2020-07-22 at 16 21 50" src="https://user-images.githubusercontent.com/397448/88224770-7667c080-cc37-11ea-8013-2545d03e079c.png">

The `NotificationsWidget` component will house a list of notifications (which will most likely be made of sub components) and some visual indications of the state of the unread notifications. In this way the widget's primary function will be the controller for unread/read state for notifications.

## API (draft)

This component is going to be a connected a container component that will be self-contained in the application. Before that happens I guess this issue should define a presentational component that can be "connected" to a data store.

```
<NotificationsWidget 
  notifications={Array<Notification>}
  notificationsRead={Array<NotificationsIds>}
  markNotificationRead={Function}
  markAllNotificationsRead={Function}
  notificationCenterLink={ReactNode}
/>
```

**Comment by dhartunian** [comment]
@nathanstilwell can I take this ticket out of Kanban for now?
